spring.application.name=secure-api
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/lab_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:lab_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:lab_password}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
jwt.expiration=3600000

logging.level.org.springframework.web=DEBUG
logging.level.com.security.lab=DEBUG
logging.level.org.springframework.security=DEBUG